/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package datasiswa;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author ithoib
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        isi.removeAll();
        isi.add(new Dashboard());
        isi.repaint();
        isi.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        sidebar = new javax.swing.JPanel();
        appTitle = new javax.swing.JLabel();
        appIcon = new javax.swing.JLabel();
        menuDasbor = new javax.swing.JPanel();
        dashIcon = new javax.swing.JLabel();
        dashLabel = new javax.swing.JLabel();
        menuJurusan = new javax.swing.JPanel();
        jurIcon = new javax.swing.JLabel();
        jurLabel = new javax.swing.JLabel();
        menuGuru = new javax.swing.JPanel();
        guruIcon = new javax.swing.JLabel();
        guruLabel = new javax.swing.JLabel();
        menuKelas = new javax.swing.JPanel();
        kelasIcon = new javax.swing.JLabel();
        kelasLabel = new javax.swing.JLabel();
        menuSiswa = new javax.swing.JPanel();
        siswaIcon = new javax.swing.JLabel();
        siswaLabel = new javax.swing.JLabel();
        menuAbout = new javax.swing.JPanel();
        aboutIcon = new javax.swing.JLabel();
        aboutLabel = new javax.swing.JLabel();
        menuLogout = new javax.swing.JPanel();
        logoutIcon = new javax.swing.JLabel();
        logoutLabel = new javax.swing.JLabel();
        main = new javax.swing.JPanel();
        isi = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        sidebar.setBackground(new java.awt.Color(41, 128, 185));

        appTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        appTitle.setForeground(new java.awt.Color(255, 255, 255));
        appTitle.setText("Aloomni");

        appIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/datasiswa/img/Book And Pencil(2).png"))); // NOI18N

        menuDasbor.setBackground(new java.awt.Color(41, 128, 185));

        dashIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/datasiswa/img/Dashboard(2).png"))); // NOI18N
        dashIcon.setToolTipText("");

        dashLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        dashLabel.setForeground(new java.awt.Color(255, 255, 255));
        dashLabel.setText("Dashboard");
        dashLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dashLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout menuDasborLayout = new javax.swing.GroupLayout(menuDasbor);
        menuDasbor.setLayout(menuDasborLayout);
        menuDasborLayout.setHorizontalGroup(
            menuDasborLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuDasborLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(dashIcon)
                .addGap(10, 10, 10)
                .addComponent(dashLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        menuDasborLayout.setVerticalGroup(
            menuDasborLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuDasborLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuDasborLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(dashLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dashIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuJurusan.setBackground(new java.awt.Color(41, 128, 185));

        jurIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/datasiswa/img/Department.png"))); // NOI18N
        jurIcon.setToolTipText("");

        jurLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jurLabel.setForeground(new java.awt.Color(255, 255, 255));
        jurLabel.setText("Jurusan");
        jurLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jurLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jurLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jurLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout menuJurusanLayout = new javax.swing.GroupLayout(menuJurusan);
        menuJurusan.setLayout(menuJurusanLayout);
        menuJurusanLayout.setHorizontalGroup(
            menuJurusanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuJurusanLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jurIcon)
                .addGap(10, 10, 10)
                .addComponent(jurLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        menuJurusanLayout.setVerticalGroup(
            menuJurusanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuJurusanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuJurusanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jurLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jurIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuGuru.setBackground(new java.awt.Color(41, 128, 185));

        guruIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/datasiswa/img/Teacher.png"))); // NOI18N
        guruIcon.setToolTipText("");

        guruLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        guruLabel.setForeground(new java.awt.Color(255, 255, 255));
        guruLabel.setText("Guru");
        guruLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guruLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                guruLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                guruLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout menuGuruLayout = new javax.swing.GroupLayout(menuGuru);
        menuGuru.setLayout(menuGuruLayout);
        menuGuruLayout.setHorizontalGroup(
            menuGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuGuruLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(guruIcon)
                .addGap(10, 10, 10)
                .addComponent(guruLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        menuGuruLayout.setVerticalGroup(
            menuGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuGuruLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(guruLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(guruIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuKelas.setBackground(new java.awt.Color(41, 128, 185));

        kelasIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/datasiswa/img/Class.png"))); // NOI18N
        kelasIcon.setToolTipText("");

        kelasLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        kelasLabel.setForeground(new java.awt.Color(255, 255, 255));
        kelasLabel.setText("Kelas");
        kelasLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kelasLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kelasLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                kelasLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout menuKelasLayout = new javax.swing.GroupLayout(menuKelas);
        menuKelas.setLayout(menuKelasLayout);
        menuKelasLayout.setHorizontalGroup(
            menuKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuKelasLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(kelasIcon)
                .addGap(10, 10, 10)
                .addComponent(kelasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        menuKelasLayout.setVerticalGroup(
            menuKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuKelasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(kelasLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kelasIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuSiswa.setBackground(new java.awt.Color(41, 128, 185));

        siswaIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/datasiswa/img/Graduate.png"))); // NOI18N
        siswaIcon.setToolTipText("");

        siswaLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        siswaLabel.setForeground(new java.awt.Color(255, 255, 255));
        siswaLabel.setText("Siswa");
        siswaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                siswaLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                siswaLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                siswaLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout menuSiswaLayout = new javax.swing.GroupLayout(menuSiswa);
        menuSiswa.setLayout(menuSiswaLayout);
        menuSiswaLayout.setHorizontalGroup(
            menuSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuSiswaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(siswaIcon)
                .addGap(10, 10, 10)
                .addComponent(siswaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        menuSiswaLayout.setVerticalGroup(
            menuSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuSiswaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(siswaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(siswaIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuAbout.setBackground(new java.awt.Color(41, 128, 185));

        aboutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/datasiswa/img/Profile.png"))); // NOI18N
        aboutIcon.setToolTipText("");

        aboutLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        aboutLabel.setForeground(new java.awt.Color(255, 255, 255));
        aboutLabel.setText("About");
        aboutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aboutLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aboutLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout menuAboutLayout = new javax.swing.GroupLayout(menuAbout);
        menuAbout.setLayout(menuAboutLayout);
        menuAboutLayout.setHorizontalGroup(
            menuAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuAboutLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(aboutIcon)
                .addGap(10, 10, 10)
                .addComponent(aboutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        menuAboutLayout.setVerticalGroup(
            menuAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(aboutLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aboutIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuLogout.setBackground(new java.awt.Color(41, 128, 185));

        logoutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/datasiswa/img/Logout(2).png"))); // NOI18N
        logoutIcon.setToolTipText("");

        logoutLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        logoutLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoutLabel.setText("Logout");
        logoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout menuLogoutLayout = new javax.swing.GroupLayout(menuLogout);
        menuLogout.setLayout(menuLogoutLayout);
        menuLogoutLayout.setHorizontalGroup(
            menuLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLogoutLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(logoutIcon)
                .addGap(10, 10, 10)
                .addComponent(logoutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        menuLogoutLayout.setVerticalGroup(
            menuLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(logoutLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(appIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(appTitle)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(menuDasbor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuJurusan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuGuru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuKelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuSiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuAbout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(appIcon))
                    .addGroup(sidebarLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(appTitle)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menuDasbor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(menuJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(menuGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(menuKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(menuSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(menuAbout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(menuLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(400, Short.MAX_VALUE))
        );

        main.setBackground(new java.awt.Color(236, 240, 241));

        isi.setBackground(new java.awt.Color(255, 255, 255));
        isi.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(isi, javax.swing.GroupLayout.DEFAULT_SIZE, 1154, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(isi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(mainPanel, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dashLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashLabelMouseEntered
        // TODO add your handling code here:
        menuDasbor.setBackground(new Color(37,117,169));
    }//GEN-LAST:event_dashLabelMouseEntered

    private void dashLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashLabelMouseExited
        // TODO add your handling code here:
        menuDasbor.setBackground(new Color(41,128,185));
    }//GEN-LAST:event_dashLabelMouseExited

    private void jurLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jurLabelMouseEntered
        // TODO add your handling code here:
        menuJurusan.setBackground(new Color(37,117,169));
    }//GEN-LAST:event_jurLabelMouseEntered

    private void jurLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jurLabelMouseExited
        // TODO add your handling code here:
        menuJurusan.setBackground(new Color(41,128,185));
    }//GEN-LAST:event_jurLabelMouseExited

    private void guruLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guruLabelMouseEntered
        // TODO add your handling code here:
         menuGuru.setBackground(new Color(37,117,169));
    }//GEN-LAST:event_guruLabelMouseEntered

    private void guruLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guruLabelMouseExited
        // TODO add your handling code here:
        menuGuru.setBackground(new Color(41,128,185));
    }//GEN-LAST:event_guruLabelMouseExited

    private void kelasLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kelasLabelMouseEntered
        // TODO add your handling code here:
        menuKelas.setBackground(new Color(37,117,169));
    }//GEN-LAST:event_kelasLabelMouseEntered

    private void kelasLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kelasLabelMouseExited
        // TODO add your handling code here:
        menuKelas.setBackground(new Color(41,128,185));
    }//GEN-LAST:event_kelasLabelMouseExited

    private void siswaLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siswaLabelMouseEntered
        // TODO add your handling code here:
        menuSiswa.setBackground(new Color(37,117,169));
    }//GEN-LAST:event_siswaLabelMouseEntered

    private void siswaLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siswaLabelMouseExited
        // TODO add your handling code here:
        menuSiswa.setBackground(new Color(41,128,185));
    }//GEN-LAST:event_siswaLabelMouseExited

    private void aboutLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutLabelMouseEntered
        // TODO add your handling code here:
        menuAbout.setBackground(new Color(37,117,169));
    }//GEN-LAST:event_aboutLabelMouseEntered

    private void aboutLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutLabelMouseExited
        // TODO add your handling code here:
        menuAbout.setBackground(new Color(41,128,185));
    }//GEN-LAST:event_aboutLabelMouseExited

    private void dashLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashLabelMouseClicked
        // TODO add your handling code here:
        menuDasbor.setBackground(new Color(37,117,169));
        isi.removeAll();
        isi.add(new Dashboard());
        isi.repaint();
        isi.revalidate();
    }//GEN-LAST:event_dashLabelMouseClicked

    private void dashLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashLabelMousePressed
        // TODO add your handling code here:
        menuDasbor.setBackground(new Color(37,117,169));
    }//GEN-LAST:event_dashLabelMousePressed

    private void logoutLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseEntered
        // TODO add your handling code here:
        menuLogout.setBackground(new Color(37,117,169));
    }//GEN-LAST:event_logoutLabelMouseEntered

    private void logoutLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseExited
        // TODO add your handling code here:
        menuLogout.setBackground(new Color(41,128,185));
    }//GEN-LAST:event_logoutLabelMouseExited

    private void jurLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jurLabelMouseClicked
        // TODO add your handling code here:
        menuJurusan.setBackground(new Color(37,117,169));
        isi.removeAll();
        isi.add(new Jurusan());
        isi.repaint();
        isi.revalidate();
    }//GEN-LAST:event_jurLabelMouseClicked

    private void guruLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guruLabelMouseClicked
        // TODO add your handling code here:
        menuGuru.setBackground(new Color(37,117,169));
        isi.removeAll();
        isi.add(new Guru());
        isi.repaint();
        isi.revalidate();
    }//GEN-LAST:event_guruLabelMouseClicked

    private void kelasLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kelasLabelMouseClicked
        // TODO add your handling code here:
        menuKelas.setBackground(new Color(37,117,169));
        isi.removeAll();
        isi.add(new Kelas());
        isi.repaint();
        isi.revalidate();
    }//GEN-LAST:event_kelasLabelMouseClicked

    private void siswaLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siswaLabelMouseClicked
        // TODO add your handling code here:
        menuSiswa.setBackground(new Color(37,117,169));
        isi.removeAll();
        isi.add(new Siswa());
        isi.repaint();
        isi.revalidate();
    }//GEN-LAST:event_siswaLabelMouseClicked

    private void aboutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutLabelMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Software ini dibuat untuk kepentingan pembelajaran JAVA \n"
                + "pada mata kuliah Pemrograman Lanjutan \n"
                + "pada Prodi S1 Sistem Informasi \n"
                + "Institut Teknologi Mojosari.","Tentang Kami",JOptionPane.PLAIN_MESSAGE);
        
    }//GEN-LAST:event_aboutLabelMouseClicked

    private void logoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseClicked
        // TODO add your handling code here:
        dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_logoutLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        </editor-fold>
        
//        try {
//            UIManager.setLookAndFeel(new FlatLightLaf());
//
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aboutIcon;
    private javax.swing.JLabel aboutLabel;
    private javax.swing.JLabel appIcon;
    private javax.swing.JLabel appTitle;
    private javax.swing.JLabel dashIcon;
    private javax.swing.JLabel dashLabel;
    private javax.swing.JLabel guruIcon;
    private javax.swing.JLabel guruLabel;
    private javax.swing.JPanel isi;
    private javax.swing.JLabel jurIcon;
    private javax.swing.JLabel jurLabel;
    private javax.swing.JLabel kelasIcon;
    private javax.swing.JLabel kelasLabel;
    private javax.swing.JLabel logoutIcon;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JPanel main;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuAbout;
    private javax.swing.JPanel menuDasbor;
    private javax.swing.JPanel menuGuru;
    private javax.swing.JPanel menuJurusan;
    private javax.swing.JPanel menuKelas;
    private javax.swing.JPanel menuLogout;
    private javax.swing.JPanel menuSiswa;
    private javax.swing.JPanel sidebar;
    private javax.swing.JLabel siswaIcon;
    private javax.swing.JLabel siswaLabel;
    // End of variables declaration//GEN-END:variables
}
